//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.Data.EFProvider.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public short CoveringPeriod { get; set; }
        public decimal PolicyRate { get; set; }
        public int CoveringTypeId { get; set; }
        public int RiskTypeId { get; set; }
        public int CustomerId { get; set; }
        public short Covering { get; set; }
        public bool State { get; set; }
    
        public virtual CoveringType CoveringType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RiskType RiskType { get; set; }
    }
}
